
STR_UP = "up"
STR_DOWN = "down"
STR_LEFT = "left"
STR_RIGHT = "right"

DISTANCES_STR = [STR_UP, STR_DOWN, STR_LEFT, STR_RIGHT]

MOVEMENTS = {
    STR_UP : [0, -1],
    STR_DOWN : [0, 1],
    STR_LEFT : [-1, 0],
    STR_RIGHT : [1, 0]
}
VALID_MOVEMENTS = {
    STR_UP  : [STR_UP, STR_LEFT, STR_RIGHT],
    STR_DOWN : [STR_DOWN, STR_LEFT, STR_RIGHT],
    STR_LEFT : [STR_DOWN, STR_UP, STR_LEFT],
    STR_RIGHT : [STR_DOWN, STR_UP, STR_RIGHT],
}


